### ISSUE TITLE
Implement OAuth Authentifcation

### ISSUE THREAD

**Issue by DSchalla** [mrshankly/go-twitch#7]
Hey @mrshankly
since I am also in need of a Twitch API Client for Go I am currently trying to integrate helpers for the OAuth Authentifcation with Twitch, including Authenticated Requests. I will try to implement the required features and will create a PR for discussion then, if requested?

**Comment by DSchalla** [comment]
First implementation in: https://github.com/mrshankly/go-twitch/pull/8

**Comment by mrshankly** [comment]
I'm very interested in having this. Thank you for working on it.

I'm a little busy these next days, I'll try to have a look at this later this week.

**Comment by DSchalla** [comment]
Sure thing. I am sure its not perfect yet, but its working so far. I am open for discussion on the exact implementation. :)
